version: "3"

tasks:
  up-db:
    desc: "Start PostgreSQL database development container"
    cmds:
      - docker compose -f docker-compose.yml up -d

  server-dev:
    desc: "Start backend server in development mode"
    dir: backend
    cmds:
      - pnpm dev

  server-build:
    desc: "Build backend server"
    dir: backend
    cmds:
      - pnpm build

  server-lint:
    desc: "Lint backend server"
    dir: backend
    cmds:
      - pnpm lint

  server-test:
    desc: "Run backend unit tests"
    dir: backend
    cmds:
      - pnpm test

  server-test-coverage:
    desc: "Run backend unit tests with coverage"
    dir: backend
    cmds:
      - pnpm test:coverage

  migrate-up:
    desc: "Run database migrations"
    dir: backend
    cmds:
      - pnpm migrate:up

  migrate-down:
    desc: "Rollback database migrations"
    dir: backend
    cmds:
      - pnpm migrate:down

  migrate-create:
    desc: "Create a new database migration"
    dir: backend
    cmds:
      - pnpm migrate:create

  frontend-dev:
    desc: "Start frontend server in development mode"
    dir: frontend
    cmds:
      - pnpm dev

  frontend-build:
    desc: "Build frontend server"
    dir: frontend
    cmds:
      - pnpm build

  frontend-lint:
    desc: "Lint frontend server"
    dir: frontend
    cmds:
      - pnpm lint

  dev:
    desc: "Start development environment"
    deps: [up-db]
    cmds:
      - task: server-dev
        async: true
      - task: frontend-dev

  build:
    desc: "Build production environment"
    cmds:
      - task: server-build
      - task: frontend-build

  lint:
    desc: "Lint code"
    cmds:
      - task: server-lint
      - task: frontend-lint

  install-backend:
    desc: "Install backend dependencies"
    dir: backend
    cmds:
      - pnpm install

  install-frontend:
    desc: "Install frontend dependencies"
    dir: frontend
    cmds:
      - pnpm install

  install:
    desc: "Install dependencies"
    cmds:
      - task: install-backend
      - task: install-frontend